### ISSUE TITLE
Does not work with Scala 2.13.x version. Scalacheck is assigned to base dependencies also. 

### ISSUE THREAD

**Issue by optical002** [mrdimosthenis/glicko2#1]
**Context:**
This library does not have built for versions 2.13.x.
So to use this plugin with scala 2.13.x, I can use cross version to use 3.x.x version as 2.13.x like this:
`("com.github.mrdimosthenis" %% "glicko2" % "1.0.0").cross(CrossVersion.for2_13Use3)`

**Problem:**
When `scalacheck` is assigned to both test and base dependencies, it fetches `scalacheck` for scala version 3 which clashes with already existing `scalacheck` for scala version 2.13.x.

**Solution:**
In build.sbt next to `scalacheck` library dependency add `% "test"` like this:
`"org.scalacheck" %%% "scalacheck" % "1.15.4" % "test"`

**Comment by mrdimosthenis** [comment]
Thank you @optical002,

I marked `scalacheck` as a **test** dependency and made a new release. Feel free to check `v1.0.1`.
